### ISSUE TITLE
geocoder api limit

### ISSUE THREAD

**Issue by WilliamBlais** [SvenSommer/MMM-GoogleAnalytics#5]
Hi,

When I set exportdatatoMMM_Globe to true, I get this error:

{ Error: Status is OVER_QUERY_LIMIT. You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_
    at /Users/williamblais/www/MagicMirror/modules/node_modules/node-geocoder/lib/geocoder/googlegeocoder.js:89:25
    at IncomingMessage.<anonymous> (/Users/williamblais/www/MagicMirror/modules/node_modules/node-geocoder/lib/httpadapter/httpadapter.js:65:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  cause: 

How can I configure geocoder to use my API key?

Thanks!
William

**Comment by SvenSommer** [comment]
Hey,
seems like your API Query limit is exceeded by the moment. Just wait a day and this error will be gone.

**Comment by SvenSommer** [comment]
Please don't hesitate to open a new issue, if you run in any other trouble.

**Comment by WilliamBlais** [comment]
@SvenSommer I've found a way to fix it! I modified the file 'node_helper.js' and put an API key in 
`var geocoder = NodeGeocoder({provider: 'google', apiKey: 'API_KEY_HERE'});`.

Would be nice to be able to modify it directly from config.js.

Btw, thanks for your awesome module :)
